from sq.gm.layers.orders.average_order import AverageOrder
from sq.gm.layers.orders.gm_order import GMOrder
from sq.gm.layers.orders.manual_order import ManualOrder
from sq.gm.layers.orders.multi_factors_1_order import MultiFactors1Order
from sq.gm.layers.orders.single_factor_1_order import SingleFactor1Order
from sq.gm.layers.orders.single_factor_2_order import SingleFactor2Order
from sq.gm.layers.orders.single_factor_3_order import SingleFactor3Order
from sq.gm.layers.orders.single_factor_4_order import SingleFactor4Order
from sq.gm.layers.orders.single_factor_5_order import SingleFactor5Order
from sq.gm.layers.orders.single_factor_6_order import SingleFactor6Order
from sq.gm.layers.orders.svm_order import SVMOrder
from sq.gm.layers.orders.vipa_order import VIPAOrder
